### ISSUE TITLE
Korean translation of Getting Started

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#37]
- [ ] Learn how Free Code Camp Works
- [ ] Create a Github Account and Join our Chat Rooms
- [ ] Configure your Code Portfolio
- [ ] Join a Campsite in Your City
- [ ] Learn What to Do If You Get Stuck

**Comment by JiwonYeom** [comment]
I'll be working on 'Learn how Free Code Camp Works'!
