### ISSUE TITLE
Brazilian Portuguese translation of Basic Front End Development Projects

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#43]
- [x] Get Set for our Front End Development Projects (@Janainaf)
- [ ]  Build a Personal Portfolio Webpage
- [ ]  Build a Random Quote Machine
- [ ]  Build a JavaScript Calculator
- [ ]  Build a Pomodoro Clock

**Comment by andreferreira-me** [comment]
@raisedadead I created the issue #86, because I think this issue is an old version of FCC. Can you close this issue? I'm working on the new issue.

**Comment by raisedadead** [comment]
Sure.
