### ISSUE TITLE
Brazilian Portuguese translation of Object Oriented and Functional Programming

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#44]
- [ ]  Declare JavaScript Objects as Variables
- [ ]  Construct JavaScript Objects with Functions
- [ ]  Make Instances of Objects with a Constructor Function
- [ ]  Make Unique Objects by Passing Parameters to our Constructor
- [ ]  Make Object Properties Private
- [ ]  Iterate over Arrays with .map
- [ ]  Condense arrays with .reduce
- [ ]  Filter Arrays with .filter
- [ ]  Sort Arrays with .sort
- [ ]  Reverse Arrays with .reverse
- [ ]  Concatenate Arrays with .concat
- [ ]  Split Strings with .split
- [ ]  Join Strings with .join

**Comment by malaquiasdev** [comment]
@raisedadead need help with this issues?

I have some free time this month.

**Comment by raisedadead** [comment]
@mmalaquias1 yes, please. You can find the guidelines here:
http://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111
