### ISSUE TITLE
Chinese translation of Gear up for Success

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/TranslationExpansion#5]
- [ ] Join our Forum
- [ ] Watch Coding Videos on our YouTube Channel
- [ ] Join our LinkedIn Alumni Network
- [ ] Commit to a Goal and a Nonprofit

**Comment by haih** [comment]
Hi Eric, The Chinese translation is still in progress? if i want to contribute my effort, what should I do?

**Comment by erictleung** [comment]
@haih the translation should still be in progress. Please refer to the [Translation Guidelines](http://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111) for more information on how to contribute. Thanks for your interest!
