### ISSUE TITLE
Brazilian Portuguese translation of Basic Algorithm Scripting

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#51]
- [x] Get Set for our Algorithm Challenges
- [x] Convert Celsius to Fahrenheit
- [x] Reverse a String
- [x] Factorialize a Number
- [x] Find the Longest Word in a String
- [x] Return Largest Numbers in Arrays
- [x] Confirm the Ending
- [x] Repeat a string repeat a string
- [x] Truncate a string
- [x] Finders Keepers
- [x] Boo who
- [x] Title Case a Sentence
- [x] Slice and Splice
- [x] Falsy Bouncer
- [x] Where do I Belong
- [x] Mutations
- [x] Chunky Monkey

**Comment by nmdoliveira** [comment]
Working on it

**Comment by raisedadead** [comment]
Thanks @nmdoliveira ! Please reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), if you need any assistance!

**Comment by nmdoliveira** [comment]
Thanks @raisedadead! Just one question, can I edit the issue description? Some challenges have been added, some removed, etc.

**Comment by raisedadead** [comment]
@nmdoliveira oh sure, please leave the updated list in the comments below, I'll take care of updating them. Thanks.

**Comment by nmdoliveira** [comment]
- [x] Get Set for our Algorithm Challenges
- [x] Convert Celsius to Fahrenheit
- [x] Reverse a String
- [x] Factorialize a Number
- [x] Find the Longest Word in a String
- [x] Return Largest Numbers in Arrays
- [x] Confirm the Ending
- [x] Repeat a string repeat a string
- [x] Truncate a string
- [x] Finders Keepers
- [x] Boo who
- [x] Title Case a Sentence
- [x] Slice and Splice
- [x] Falsy Bouncer
- [x] Where do I Belong
- [x] Mutations
- [x] Chunky Monkey

**Comment by nmdoliveira** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/14590
