### ISSUE TITLE
Brazilian Portuguese translation of Getting Started

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#55]
- [x] Learn how Free Code Camp Works Complete
- [x] Create a GitHub Account and Join our Chat Rooms Complete
- [x] Configure your Code Portfolio Complete
- [x] Join a Campsite in Your City Complete
- [x] Read Coding News on our Medium Publication
- [ ] Learn What to Do If You Get Stuck

**Comment by samanthakem** [comment]
Working on it

**Comment by samanthakem** [comment]
I finished up the **Getting Started - Learn how Free Code Camp Works** session. Could someone please review my PR in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10390 ? Thanks.

**Comment by samanthakem** [comment]
Learn how Free Code Camp Works [**DONE**]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10994

Create a GitHub Account and Join our Chat Rooms [**DONE**]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11013

Configure your Code Portfolio | Join a Campsite in Your City | Read Coding News on our Medium Publication [**DONE**]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11023

Learn What to Do If You Get Stuck [**DONE**]
https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11028

**Comment by samanthakem** [comment]
Create a GitHub Account and Join our Chat Rooms [REVIEW] https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11013

**Comment by samanthakem** [comment]
Configure your Code Portfolio [**REVIEW**] https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11023**

**Comment by samanthakem** [comment]
@raisedadead there's another sub-section in Getting Started section: "Read Coding News on our Medium Publication"

It is between **Join a Campsite in Your City** and **Learn What to Do If You Get Stuck**

**Comment by justincorrigible** [comment]
Fixed :) Thanks!

**Comment by samanthakem** [comment]
@hallaathrad @raisedadead  feel free to update the description of this issue or close it. Translation of Getting Started into PT-BR is officially done! (all PRs have been merged) 💃

**Comment by ghost** [comment]
:tada:

**Comment by samanthakem** [comment]
Thanks @atjonathan :)
