### ISSUE TITLE
French translation of Basic Front End Development Projects

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#64]
@atjonathan commented on [Sat Mar 19 2016](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7634)
- [ ] Get Set for our Front End Development Projects
- [ ] Build a Tribute Page 
- [ ] Build a Personal Portfolio Webpage

**Comment by thomaslombart** [comment]
That one can be closed as it is handled in the Responsive Web Design part : #93
