### ISSUE TITLE
French translation of JSON APIs and Ajax

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#68]
@atjonathan commented on [Sat Mar 19 2016](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7638)
- [ ] Trigger Click Events with jQuery 
- [ ] Change Text with Click Events 
- [ ] Get JSON with the jQuery getJSON Method 
- [ ] Convert JSON Data to HTML 
- [ ] Render Images from Data Sources 
- [ ] Prefilter JSON 
- [ ] Get Geo-location Data

**Comment by thomaslombart** [comment]
It is now in data Visualization part, so this issue can be closed as translation will be handled in #78
