### ISSUE TITLE
French translation of Intermediate Front End Development Projects

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#69]
@atjonathan commented on [Sat Mar 19 2016](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7639)
- [ ] Build a Random Quote Machine 
- [ ] Show the Local Weather 
- [ ] Build a Wikipedia Viewer 
- [ ] Use the Twitch.tv JSON API 

---

@elazzabi commented on [Fri May 20 2016](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7639#issuecomment-220445266)

Working on it

**Comment by thomaslombart** [comment]
That one can be closed as it is handled in the Responsive Web Design part : #93
