### ISSUE TITLE
French translation of Data Visualization

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#78]
Refer older issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7648
- [ ] Data Visualization with D3
- [ ] JSON APIs and AJAX
- [ ] Data Visualization Projects
- [ ] Claim Your Data Visualization Certificate

**Comment by thomaslombart** [comment]
That part can become Data Visualization and contains : 

- [ ] Data Visualization with D3

- [ ] JSON APIs and AJAX

- [ ] Data Visualization Projects

- [ ] Claim Your Data Visualization Certificate
