### ISSUE TITLE
French translation of API and Microservices

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#80]
Refer older issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7651
- [ ] Managing Packages with 
- [ ] Basic Node and Express
- [ ] MongoDB and Mongoose
- [ ] API and Microservice Projects
- [ ] Claim Your APIs and Microservices Certificate

**Comment by thomaslombart** [comment]
That part can be renamed to APIs and Microservices 

It contains now : 

- [ ] Managing Packages with 

- [ ] Basic Node and Express

- [ ] MongoDB and Mongoose

- [ ] API and Microservice Projects

- [ ] Claim Your APIs and Microservices Certificate
