### ISSUE TITLE
French translation of Coding Interview and Take Home Projects

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#81]
Refer older issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7652
- [ ] Show the local Weather
- [ ] Build a Wikipedia Viewer
- [ ] Use the Twitch.tv JSON API
- [ ] Build a Tic Tac Toe Game
- [ ] Build a Simon Game
- [ ] Build a Camper Leaderboard
- [ ] Build a Recipe Box
- [ ] Build the Game of Life
- [ ] Build a Roguelike Dungeon Crawler Game
- [ ] P2P Video Chat Application
- [ ] Show National Contiguity with a Force Directed Graph
- [ ] Map Data Across the Globe
- [ ] Manage a Book Trading Club
- [ ] Build a Pinterest Clone

**Comment by thomaslombart** [comment]
As dynamic web application projects doesn't exist in the new curriculum, this should be updated as the Coding Interview Take-home Projects : 

- [ ] Show the local Weather
- [ ] Build a Wikipedia Viewer
- [ ] Use the Twitch.tv JSON API
- [ ] Build a Tic Tac Toe Game
- [ ] Build a Simon Game
- [ ] Build a Camper Leaderboard
- [ ] Build a Recipe Box
- [ ] Build the Game of Life
- [ ] Build a Roguelike Dungeon Crawler Game
- [ ] P2P Video Chat Application
- [ ] Show National Contiguity with a Force Directed Graph
- [ ] Map Data Across the Globe
- [ ] Manage a Book Trading Club
- [ ] Build a Pinterest Clone
