### ISSUE TITLE
Brazilian Portuguese translation of Advanced Ziplines

### ISSUE THREAD

**Issue by andreferreira-me** [freeCodeCamp/TranslationExpansion#86]
- [x] Build a JavaScript Calculator
- [x] Build a Pomodoro Clock
- [x] Build a Tic Tac Toe Game
- [x] Build a Simon Game

**Comment by andreferreira-me** [comment]
Working on it!

**Comment by andreferreira-me** [comment]
@raisedadead @samanthakem Can you review my PR ?

Advanced Ziplines translated into Brazilian Portuguese [**DONE**]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11333

**Comment by raisedadead** [comment]
thanks @andreferreira-me, please get it reviewed from a peer as well.
