### ISSUE TITLE
Indonesian Translation of Getting Started

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#87]
Opened by @baguzzzaji via https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8025#issue-147207550

**Comment by ghost** [comment]
Is it done? 

If there stil anything that hasn't been done I'll be happy to help 😉

**Comment by raisedadead** [comment]
@christoga head over to the https://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111 and proceed with the instructions.

**Comment by ghost** [comment]
Thanks @raisedadead
