### ISSUE TITLE
Update Translation Guide

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/TranslationExpansion#90]
We need to update the translation guide, to the latest steps.

- [x] Add steps to create a test instance of freeCodeCamp with the translations activated. Done by @Dagolin 
- [ ] Update the GIF recordings and steps to create translation issues.
- [ ] Update the GIF recordings and steps to create translation pull requests.
- [ ] Clean up the guide for old stale steps and text.

Refer guide link : 
https://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111

**Comment by Dagolin** [comment]
@raisedadead Sorry for the late reply, I just updated the guide and please feel free to update it.

[https://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111](https://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111)

**Comment by raisedadead** [comment]
Thanks for the contribution @Dagolin ! I have updated the issue a little bit more, to break into smaller chunks.

**Comment by Dagolin** [comment]
Update the GIF recordings and steps to create translation issues. "Working on it"

**Comment by Dagolin** [comment]
https://forum.freecodecamp.com/t/guidelines-for-translating-free-code-camp-to-any-language/19111/3
