### ISSUE TITLE
Brazilian Portuguese translation of Basic HTML and HTML5

### ISSUE THREAD

**Issue by nmdoliveira** [freeCodeCamp/TranslationExpansion#92]
- [x] Introduction to the Basic HTML and HTML5 Challenges
- [x] Say Hello to HTML Elements
- [x] Headline with the h2 Element
- [x] Inform with the Paragraph Element
- [x] Fill in the Blank with Placeholder Text
- [x] Uncomment HTML
- [x] Comment out HTML
- [x] Delete HTML Elements
- [x] Introduction to HTML5 Elements
- [x] Add Images to your Website
- [x] Link to External Pages with Anchor Elements
- [x] Link to Internal Section of a Page with Anchor Elements
- [x] Nest an Anchor Element within a Paragraph
- [x] Make Dead Links using the Hash Symbol
- [x] Turn an Image into a Link
- [x] Create a Bulleted Unordered List
- [x] Create an Ordered List
- [x] Create a Text Field
- [x] Add Placeholder Text to a Text Field
- [x] Create a Form Element
- [x] Add a Submit Button to a Form
- [x] Use HTML5 to Require a Field
- [x] Create a Set of Radio Buttons
- [x] Create a Set of Checkboxes
- [x] Check Radio Buttons and Checkboxes by Default
- [x] Nest Many Elements within a Single Div Element
- [x] Declare the Doctype of an HTML Document
- [x] Define the Head and Body of an HTML Document

**Comment by nmdoliveira** [comment]
Working on it

**Comment by luizasribeiro** [comment]
Olá, gostaria de ajudar a traduzir para o Português. Mas não tenho experiência com o Github. Vc quer ajuda?

**Comment by aferreira44** [comment]
Olá @nmdoliveira, como está indo a tradução? Quer ajuda?

Vou começar a traduzir outra seção, mas se precisar de ajuda, posso ajudar para terminarmos essa primeiro.

**Comment by nmdoliveira** [comment]
Oi @luizasribeiro, @aferreira44! Desculpem a demora para responder, tive uns problemas e parei de trabalhar nessa tradução por um tempo.
Mas agora eu vou voltar, acho que termino essa semana mesmo, espero que um de vocês possa revisar!
Pelo que eu vi, parece que essa seção foi quebrada em duas (Basic HTML and HTML5 / Basic CSS), então vou alterar essa issue pra Basic HTML and HTML5.

**Comment by aferreira44** [comment]
Legal @nmdoliveira! Claro, quando terminar só dar um toque aqui que ajudo a revisar sim.

**Comment by nmdoliveira** [comment]
Terminei!
@aferreira44, quando puder revisar: https://github.com/freeCodeCamp/freeCodeCamp/pull/15439
